### ISSUE TITLE
Add "Kingdom Credit" tracking

### ISSUE THREAD

**Issue by BitTim** [BitTim/VexTrack#84]
Kingdom Credit is a new ingame currency added to Valorant which is earned by playing he game. It can be used to buy collectables from gears, the new agent contracts, and collectables from battlepasses from past seasons

### Frontend:
- [ ] When crating a history entry there should also be a field to enter the amount of Kingdom Credit gained
- [ ] Add Kingdom Credit counter in new "Collection" secreen
- [ ] Show each collectable from agent gears that one can afford in a section of the "Collection" screen
- [ ] Keep track of transactions in new "Transactions" section in "History" screen

### Backend:
- [ ] Transactions should have a UUID, Amount, Timestamp and RelationUUID to have a point of relation what caused the transaction (HistoryEntry or Purchase)
- [ ] Transaction history should be saved separately from XP History but have a similar strructure
